name: Build glossary
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 */12 * * *'

jobs:
  run:
    name: Build glossary
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up ruby
      uses: ruby/setup-ruby@v1

    - name: Install dependencies
      run: script/bootstrap

    - name: Rebuild glossary
      run: ruby build.rb
      env:
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

    - name: Commit changes to gh-pages branch
      uses: crazy-max/ghaction-github-pages@v4
      with:
        build_dir: "dist"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
