name: Tests

on:
  pull_request:
    branches:
      - master

jobs:
  run:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up ruby
      uses: ruby/setup-ruby@v1

    - name: Run tests
      run: script/test
